#!/usr/bin/env bash
# Start the host-side Claude bridge (n8n/host-bridge/claude-bridge.mjs) in the background.
# The bridge exposes the host's `claude` CLI to workflows running in the n8n container.
#
# Reads CLAUDE_BRIDGE_TOKEN from n8n/.env.sandbox (generated by sandbox-up.sh).
#
# Usage: ./scripts/bridge-up.sh
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." &>/dev/null && pwd)"
ENV_FILE="$REPO_ROOT/.env.sandbox"
BRIDGE_DIR="$REPO_ROOT/host-bridge"
BRIDGE_JS="$BRIDGE_DIR/claude-bridge.mjs"
PID_FILE="$BRIDGE_DIR/.bridge.pid"
LOG_FILE="$BRIDGE_DIR/.bridge.log"

_log() { echo "[bridge-up] $*" >&2; }

command -v node >/dev/null 2>&1 || { _log "FATAL: node is required on the host"; exit 1; }
command -v claude >/dev/null 2>&1 || _log "WARN: 'claude' CLI not on PATH — /health will fail"

if [ ! -f "$ENV_FILE" ]; then
	_log "FATAL: $ENV_FILE not found — run scripts/sandbox-up.sh first"
	exit 1
fi

# shellcheck disable=SC1090
set -a
. "$ENV_FILE"
set +a

if [ -z "${CLAUDE_BRIDGE_TOKEN:-}" ]; then
	_log "FATAL: CLAUDE_BRIDGE_TOKEN not set in $ENV_FILE"
	exit 1
fi

if [ -f "$PID_FILE" ] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
	_log "bridge already running (pid $(cat "$PID_FILE"))"
	exit 0
fi

mkdir -p "$BRIDGE_DIR/.jobs"
nohup node "$BRIDGE_JS" >"$LOG_FILE" 2>&1 &
echo $! > "$PID_FILE"
sleep 1
if ! kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
	_log "FATAL: bridge exited immediately; see $LOG_FILE"
	tail -n 40 "$LOG_FILE" >&2 || true
	rm -f "$PID_FILE"
	exit 1
fi
_log "bridge started (pid $(cat "$PID_FILE")), log $LOG_FILE"
